export default {
    en: {
        "finishText": "Thank You!",
        "pageNotFound": "PAGE NOT FOUND",
        "goToCatalog": "Go to Catalog",
        "Username": "Username",
        "City": "City",
        "Postal Code": "Postal Code",
        "Submit": "Submit",
        "Clear Values": "Clear Values",
        "Email": "Email",
        "Catalog": "Catalog",
        "Order": "Order",
        "Basket": "Basket",
        "TotalPrice": "Total Price",
        "BackToCatalog": "Back to Catalog",
        "empty": "Basket is empty!",
    },
    uk: {
        "finishText": "Дякую!",
        "pageNotFound": "СТОРІНКУ НЕ ЗНАЙДЕНО",
        "goToCatalog": "До каталогу",
        "Username": "Ім'я користувача",
        "City": "Місто",
        "Postal Code": "Поштовий індекс",
        "Submit": "Надіслати",
        "Clear Values": "Очистити поля",
        "Email": "Електронна пошта",
        "Catalog": "Каталог",
        "Order": "Замовлення",
        "Basket": "Кошик",
        "TotalPrice": "Загальна сума",
        "BackToCatalog": "До каталогу",
        "empty": "Кошик порожній!",
    }
}